import { guideSchema, type Guide } from '@reforma-digital/core';

/** Public-source candidates. They stay pending until the source and publication gates approve them. */
export const unemploymentGuides: Guide[] = [
  guideSchema.parse({
    id: 'catalunya-unemployment-self-employment',
    revision: 1,
    title: {
      ca: 'Atur, inici d’activitat i cessament',
      es: 'Desempleo, inicio de actividad y cese',
    },
    domain: 'D-05',
    subtopic: 'unemployment-self-employment',
    profiles: ['contributory', 'subsidy', 'self-employed'],
    jurisdiction: 'ES-CT',
    consultedAt: '2026-10-04',
    period: { evidenceIds: [] },
    validation: { status: 'pending' },
    evidence: [
      {
        id: 'boe-33',
        sourceId: 'BOE-A-2007-13409',
        url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2007-13409#a33',
        originalUrl: 'https://www.boe.es/buscar/act.php?id=BOE-A-2007-13409#a33',
        version: 'art33-2015-10-10',
        language: 'es',
        attribution: 'BOE, Ley 20/2007, artículo 33; texto consolidado informativo',
        sourceUpdatedAt: '2015-09-10',
        applicableFrom: '2015-10-10',
        applicableUntil: null,
        informative: true,
        jurisdiction: 'ES',
        quote: 'los titulares del derecho a la prestación por desempleo de nivel contributivo',
      },
      {
        id: 'boe-33-cap',
        sourceId: 'BOE-A-2007-13409',
        url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2007-13409#a33',
        originalUrl: 'https://www.boe.es/buscar/act.php?id=BOE-A-2007-13409#a33',
        version: 'art33-2015-10-10',
        language: 'es',
        attribution: 'BOE, Ley 20/2007, artículo 33; texto consolidado informativo',
        sourceUpdatedAt: '2015-09-10',
        applicableFrom: '2015-10-10',
        applicableUntil: null,
        informative: true,
        jurisdiction: 'ES',
        quote: 'por un máximo de 270 días o por el tiempo inferior pendiente de percibir',
      },
      {
        id: 'boe-33-exclusions',
        sourceId: 'BOE-A-2007-13409',
        url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2007-13409#a33',
        originalUrl: 'https://www.boe.es/buscar/act.php?id=BOE-A-2007-13409#a33',
        version: 'art33-2015-10-10',
        language: 'es',
        attribution: 'BOE, Ley 20/2007, artículo 33; texto consolidado informativo',
        sourceUpdatedAt: '2015-09-10',
        applicableFrom: '2015-10-10',
        applicableUntil: null,
        informative: true,
        jurisdiction: 'ES',
        quote: 'aquellas personas cuyo último empleo haya sido por cuenta propia',
      },
      {
        id: 'boe-34',
        sourceId: 'BOE-A-2007-13409',
        url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2007-13409#a34',
        originalUrl: 'https://www.boe.es/buscar/act.php?id=BOE-A-2007-13409#a34',
        version: 'art34-corrected-2016-01-14',
        language: 'es',
        attribution: 'BOE, Ley 20/2007, artículo 34; texto consolidado informativo',
        sourceUpdatedAt: '2016-01-14',
        applicableFrom: '2015-10-10',
        applicableUntil: null,
        informative: true,
        jurisdiction: 'ES',
        quote:
          'La entidad gestora podrá abonar a los beneficiarios de prestaciones por desempleo de nivel contributivo',
      },
      {
        id: 'sepe-capitalization',
        sourceId: 'SEPE-capitaliza-tu-prestacion',
        url: 'https://sepe.es/HomeSepe/autonomos/capitaliza-tu-prestacion.html',
        originalUrl: 'https://sepe.es/HomeSepe/autonomos/capitaliza-tu-prestacion.html',
        version: 'undated-observed-2026-10-04',
        language: 'es',
        attribution: 'SEPE, Capitaliza tu prestación; fecha de actualización no publicada',
        sourceUpdatedAt: null,
        applicableFrom: '2026-10-04',
        applicableUntil: null,
        informative: true,
        jurisdiction: 'ES',
        quote: 'La fecha de la solicitud debe ser anterior a la fecha de incorporación',
      },
      {
        id: 'soc-capitalization',
        sourceId: 'SOC-capitalitzacio-atur',
        url: 'https://serveiocupacio.gencat.cat/ca/detall/article/Capitalitzacio-de-latur',
        originalUrl: 'https://serveiocupacio.gencat.cat/ca/detall/article/Capitalitzacio-de-latur',
        version: '2026-06-16',
        language: 'ca',
        attribution: 'Servei Públic d’Ocupació de Catalunya, Capitalització de l’atur',
        sourceUpdatedAt: '2026-06-16',
        applicableFrom: '2026-06-16',
        applicableUntil: null,
        informative: true,
        jurisdiction: 'ES-CT',
        quote:
          'Telemàticament a través de la Seu Electrònica del Servicio Público de Empleo Estatal',
      },
      {
        id: 'boe-271',
        sourceId: 'BOE-A-2015-11724',
        url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2015-11724#a271',
        originalUrl: 'https://www.boe.es/buscar/act.php?id=BOE-A-2015-11724#a271',
        version: 'art271-2026-02-04',
        language: 'es',
        attribution:
          'BOE, Ley General de la Seguridad Social, artículo 271; texto consolidado informativo',
        sourceUpdatedAt: '2026-02-04',
        applicableFrom: '2026-02-04',
        applicableUntil: null,
        informative: true,
        jurisdiction: 'ES',
        quote: 'mientras el titular del derecho realice un trabajo por cuenta propia',
      },
      {
        id: 'boe-271-resumption',
        sourceId: 'BOE-A-2015-11724',
        url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2015-11724#a271',
        originalUrl: 'https://www.boe.es/buscar/act.php?id=BOE-A-2015-11724#a271',
        version: 'art271-2026-02-04',
        language: 'es',
        attribution:
          'BOE, Ley General de la Seguridad Social, artículo 271; texto consolidado informativo',
        sourceUpdatedAt: '2026-02-04',
        applicableFrom: '2026-02-04',
        applicableUntil: null,
        informative: true,
        jurisdiction: 'ES',
        quote: 'El derecho a la reanudación nacerá a partir del término de la causa de suspensión',
      },
      {
        id: 'boe-330',
        sourceId: 'BOE-A-2015-11724',
        url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2015-11724#a330',
        originalUrl: 'https://www.boe.es/buscar/act.php?id=BOE-A-2015-11724#a330',
        version: 'art330-2023-03-02',
        language: 'es',
        attribution:
          'BOE, Ley General de la Seguridad Social, artículo 330; texto consolidado informativo',
        sourceUpdatedAt: '2023-03-01',
        applicableFrom: '2023-03-02',
        applicableUntil: null,
        informative: true,
        jurisdiction: 'ES',
        quote: 'Encontrarse en situación legal de cese de actividad',
      },
      {
        id: 'boe-337',
        sourceId: 'BOE-A-2015-11724',
        url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2015-11724#a337',
        originalUrl: 'https://www.boe.es/buscar/act.php?id=BOE-A-2015-11724#a337',
        version: 'art337-2022-10-07',
        language: 'es',
        attribution:
          'BOE, Ley General de la Seguridad Social, artículo 337; texto consolidado informativo',
        sourceUpdatedAt: '2022-09-07',
        applicableFrom: '2022-10-07',
        applicableUntil: null,
        informative: true,
        jurisdiction: 'ES',
        quote:
          'deberán solicitar a la mutua colaboradora con la Seguridad Social a la que se encuentren adheridos',
      },
      {
        id: 'boe-338',
        sourceId: 'BOE-A-2015-11724',
        url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2015-11724#a338',
        originalUrl: 'https://www.boe.es/buscar/act.php?id=BOE-A-2015-11724#a338',
        version: 'art338-2023-01-01',
        language: 'es',
        attribution:
          'BOE, Ley General de la Seguridad Social, artículo 338; texto consolidado informativo',
        sourceUpdatedAt: '2022-07-27',
        applicableFrom: '2023-01-01',
        applicableUntil: null,
        informative: true,
        jurisdiction: 'ES',
        quote:
          'al menos, doce meses deben estar comprendidos en los veinticuatro meses inmediatamente anteriores',
      },
    ],
    conditions: [
      {
        id: 'contributory',
        text: {
          ca: 'Si cobres una prestació contributiva per desocupació, identifica si encara no has començat l’activitat.',
          es: 'Si cobras una prestación contributiva por desempleo, identifica si aún no has iniciado la actividad.',
        },
        evidenceIds: ['boe-33', 'boe-34'],
        translation: 'ca',
      },
      {
        id: 'suspended',
        text: {
          ca: 'Si la prestació per desocupació està suspesa per treball per compte propi, la represa és una ruta diferent de la compatibilitat.',
          es: 'Si la prestación por desempleo está suspendida por trabajo por cuenta propia, la reanudación es una ruta distinta de la compatibilidad.',
        },
        evidenceIds: ['boe-271', 'boe-271-resumption'],
        translation: 'ca',
      },
      {
        id: 'cessation',
        text: {
          ca: 'Si cesses una activitat autònoma, identifica la causa, la cobertura i les cotitzacions abans de valorar la prestació per cessament.',
          es: 'Si cesas una actividad autónoma, identifica la causa, la cobertura y las cotizaciones antes de valorar la prestación por cese.',
        },
        evidenceIds: ['boe-330', 'boe-337', 'boe-338'],
        translation: 'ca',
      },
    ],
    exclusions: [
      {
        id: 'subsidy-exclusion',
        text: {
          ca: 'La compatibilitat de la prestació contributiva no determina la compatibilitat d’un subsidi.',
          es: 'La compatibilidad de la prestación contributiva no determina la compatibilidad de un subsidio.',
        },
        evidenceIds: ['boe-33'],
        translation: 'ca',
      },
    ],
    claims: [
      {
        id: 'compatibility',
        kind: 'fact',
        text: {
          ca: 'La llei preveu compatibilitat de la prestació contributiva amb l’activitat autònoma fins a 270 dies o el període pendent inferior, amb requisits i exclusions.',
          es: 'La ley prevé compatibilidad de la prestación contributiva con la actividad autónoma hasta 270 días o el periodo pendiente inferior, con requisitos y exclusiones.',
        },
        evidenceIds: ['boe-33', 'boe-33-cap', 'boe-33-exclusions'],
        translation: 'ca',
        conditionIds: ['contributory'],
      },
      {
        id: 'capitalization',
        kind: 'fact',
        text: {
          ca: 'La capitalització és una via diferent per a la prestació contributiva. La sol·licitud s’ha de fer abans de l’inici; el SOC enllaça a la seu del SEPE.',
          es: 'La capitalización es una vía distinta para la prestación contributiva. La solicitud debe hacerse antes del inicio; el SOC enlaza a la sede del SEPE.',
        },
        evidenceIds: ['boe-34', 'sepe-capitalization', 'soc-capitalization'],
        translation: null,
        conditionIds: ['contributory'],
      },
      {
        id: 'suspension',
        kind: 'fact',
        text: {
          ca: 'El treball per compte propi pot suspendre la prestació per desocupació; la represa depèn del supòsit i del període.',
          es: 'El trabajo por cuenta propia puede suspender la prestación por desempleo; la reanudación depende del supuesto y del periodo.',
        },
        evidenceIds: ['boe-271', 'boe-271-resumption'],
        translation: 'ca',
        conditionIds: ['suspended'],
      },
      {
        id: 'cessation-protection',
        kind: 'fact',
        text: {
          ca: 'La protecció per cessament es tramita davant la mútua o entitat gestora corresponent; la llei exigeix almenys dotze mesos de cotització dins dels vint-i-quatre anteriors.',
          es: 'La protección por cese se tramita ante la mutua o entidad gestora correspondiente; la ley exige al menos doce meses de cotización dentro de los veinticuatro anteriores.',
        },
        evidenceIds: ['boe-337', 'boe-338'],
        translation: 'ca',
        conditionIds: ['cessation'],
      },
    ],
    steps: [],
  }),
  guideSchema.parse({
    id: 'catalunya-youth-self-employment-2026-history',
    revision: 1,
    title: {
      ca: 'Ajut a l’autoocupació juvenil 2026: convocatòria tancada',
      es: 'Ayuda al autoempleo juvenil 2026: convocatoria cerrada',
    },
    domain: 'D-05',
    subtopic: 'youth-grant-history',
    profiles: ['young-self-employed'],
    jurisdiction: 'ES-CT',
    consultedAt: '2026-10-04',
    period: { until: '2026-09-22', evidenceIds: ['gencat-2026'] },
    validation: { status: 'pending' },
    evidence: [
      {
        id: 'gencat-2026',
        sourceId: 'EMT-2615-2026',
        url: 'https://tramits.gencat.cat/ca/tramits/tramits-temes/Subvencions-per-afavorir-lautoocupacio-de-joves-en-el-marc-del-Programa-FSE-00001?moda=1',
        originalUrl:
          'https://tramits.gencat.cat/ca/tramits/tramits-temes/Subvencions-per-afavorir-lautoocupacio-de-joves-en-el-marc-del-Programa-FSE-00001?moda=1',
        version: 'EMT-2615-2026',
        language: 'ca',
        attribution: 'Tràmits Gencat, convocatòria EMT/2615/2026',
        sourceUpdatedAt: '2026-07-27',
        applicableFrom: '2026-07-28',
        applicableUntil: '2026-09-22',
        informative: true,
        jurisdiction: 'ES-CT',
        quote: 'fins al 22 de setembre de 2026, a les 14:00 h',
      },
    ],
    conditions: [],
    exclusions: [],
    claims: [
      {
        id: 'closed-call',
        kind: 'fact',
        text: {
          ca: 'El termini de sol·licitud de la convocatòria juvenil 2026 va acabar el 22 de setembre de 2026 a les 14:00 h. Aquesta fitxa és històrica.',
          es: 'El plazo de solicitud de la convocatoria juvenil 2026 terminó el 22 de septiembre de 2026 a las 14:00 h. Esta ficha es histórica.',
        },
        evidenceIds: ['gencat-2026'],
        translation: 'es',
        conditionIds: [],
      },
    ],
    steps: [],
  }),
];

/** Outstanding inputs prevent a personal recommendation or an automated submission. */
export const unemploymentCoverage = {
  questions: [
    'Tipo y estado de prestación, fecha de inicio o cese y régimen de protección',
    'Uso previo de compatibilidad o pago único y relación con el último empleador',
    'Causa acreditada del cese, mutua y periodos cotizados',
  ],
  unresolved: [
    'El artículo 33 dice 15 días; un resumen SEPE dice 15 días hábiles: no calcular vencimiento.',
    'Un resumen TGSS contradice el artículo 338 sobre continuidad de cotizaciones: no decidir elegibilidad desde ese resumen.',
    'Subsidios, capitalización por tipo de autónomo y nuevas convocatorias requieren fichas y versiones propias.',
  ],
} as const;
